add-bookings  - 14 спринт
lap-lik/java-shareit pull request #2
Opened 2024-04-14 16:26 UTC by lap-lik

2024-04-19 20:52 UTC, Fleaman777 requested changes

2024-04-19 20:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingResponseDto approvedBooking(Long userId, Long bookingId, boolean approved);
Возможно, название метода approvedBooking может ввести в заблуждение. Лучше использовать approveBooking

2024-04-19 20:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
чем-то обосновано использование разных FetchType для @ManyToOne ? 
если нет, можно сделать lazy, что бы не поймать проблему n+1 и соответственно замеддение работы с бд

2024-04-19 20:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isItemExists) {
в целом в if можно сразу использовать itemDao.existsItemByIdAndOwner_Id(itemId, bookerId), что бы не создавать лишние переменные

2024-04-19 20:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    List<Item> findAllByNameContainingIgnoreCaseAndAvailableTrueOrDescriptionContainingIgnoreCaseAndAvailableTrue(String name, String description);
выглядит внушительно) 

но достаточно сложен для восприятия из-за его длины и структуры. Рекомендую разделить его на более мелкие части или использовать аннотацию @Query для большей читаемости и управляемости запросом. Так будет проще поддерживать и оптимизировать код в будущем

2024-04-19 20:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
переменная now используется только в конце метода и только в вызове getItemWithBookingsAndCommentsDto. Лучше переместить её объявление ближе к месту использования, чтобы улучшить читаемость и избежать лишних вызовов в случаях, когда метод может завершиться раньше.

2024-04-19 21:36 UTC, lap-lik commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingResponseDto approvedBooking(Long userId, Long bookingId, boolean approved);
Исправил.
Все еще путаю как называть методы и переменные.

2024-04-19 21:42 UTC, lap-lik commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
это неисправленный артефакт - Исправил.
долго не мог понять почему не подгружаются данные этого поля для responseDto в методе create, много где правил код тестируя почему не грузится. 
теперь знаю что это из-за кеширования данных в пределах одной транзакции.

2024-04-19 21:48 UTC, lap-lik commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isItemExists) {
Исправил, мне казалось так читаемость кода лучше.

2024-04-19 21:59 UTC, lap-lik commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
Исправил, действительно нет смысла создавать переменную если после есть вероятность завершения метода с ошибкой.
Но не согласен про вызов в приватном методе getItemWithBookingsAndCommentsDto, ведь для получения всех итемов создателя, запускается цикл и каждый раз эта переменная будет создаваться заново и меняться. Точка отсчета для каждого итема тогда будет своя.

2024-04-19 22:11 UTC, lap-lik commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    List<Item> findAllByNameContainingIgnoreCaseAndAvailableTrueOrDescriptionContainingIgnoreCaseAndAvailableTrue(String name, String description);
Исправил.
Интересно что преподаватель сказал лучше писать запросные методы чем nativeQuery.
Есть какое-то разумное ограничение по количеству операндов в запросном методе?

2024-04-20 06:26 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
здорово, что разобрался

2024-04-20 11:19 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    List<Item> findAllByNameContainingIgnoreCaseAndAvailableTrueOrDescriptionContainingIgnoreCaseAndAvailableTrue(String name, String description);
не видел какого-то определенного ограничения по количеству символов/операндов для названия, здесь больше на внутреннее ощущение, что много)

просто в теории может возникнуть проблема с производительсностью, т.к далеко не факт, что SPring JPA построит этот запрос оптимально, вручную это больше контроллируется, 
конкретно в твоем случае может итоговый запрос и не будет сложным, но что бы в будущем не нарваться на просадку по перфомансу, лучше таким вещам уделять чуть больше внимания

2024-04-20 11:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
ну да, здесь ты правильно говоришь, что создать переменную лучше перед циклом

2024-04-20 11:21 UTC, Fleaman777 approved these changes

2024-04-20 11:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +                    "OR (description ILIKE CONCAT('%', :text, '%') AND available = TRUE);")
👍

2024-04-21 17:20 UTC, merged