feach: добавить функционал 16 спринта
lap-lik/java-shareit pull request #4
Opened 2024-05-12 18:17 UTC by lap-lik

2024-05-13 20:16 UTC, Fleaman777 requested changes

2024-05-13 20:16 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:16.1
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2024-05-13 20:16 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        }
подобная валидация должна быть либо на уровне сервис, либо в отдельном валидатор классе. 
так будет соблюдаться принцип разделения ответсвенности, каждый spring компонент будет отвечать за свою логику

2024-05-13 20:16 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/client/BookingClient.java
> +        String url = String.format("/owner?state=%s&from=%d&size=%d", state.name(), from, size);
подобные пути тоже хорошо бы выносить в константы, а то и вообще в пропертис, так будет ими удобней управлять в одном предноначенном для этого месте

2024-05-13 20:16 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +            return ResponseEntity.status(e.getStatusCode()).body(e.getResponseBodyAsByteArray());
можно было бы еще добавить лог, о том, что именно могло пойти не так

2024-05-13 20:16 UTC, Fleaman777 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
можно использовать такую конструкцию: shareit-server.url=${SHAREIT_SERVER_URL:http://localhost:9090}
она означает, что если, в докер-компосе не просетать переменную SHAREIT_SERVER_URL, то будет использоваться дефлотное значение http://localhost:9090/

2024-05-13 20:56 UTC, lap-lik commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
Выполнил. 
Изначально реализовал в таком варианте - shareit-server.url=${SHAREIT_SERVER_URL}
Но когда столкнулся что при запуске контейнеров не проходило 85 тестов постмана, все переписал искал в чем может быть ошибка. Оказалось фейл 85 тестов это нормально из-за environment.

2024-05-13 23:06 UTC, lap-lik commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        }
Создал отдельный компонент BookingValidator.

2024-05-13 23:17 UTC, lap-lik commented on gateway/src/main/java/ru/practicum/shareit/booking/client/BookingClient.java
> +        String url = String.format("/owner?state=%s&from=%d&size=%d", state.name(), from, size);
Вынес урлы в константы. 

Три часа пытался реализовать урлы в application.properties, не проходит тесты.
Пробовал варьировать уровни доступа менял на статик, менял названия и положения в properties. 
Не удалось победить. 
Кстати константа API тоже не хочет устанавливаться из properties, так как ей необходимо иметь уровень доступа pfs.

Вариант моего кода для метода get:

```java
@Service
public class BookingClient extends BaseClient {

    @Value("${booking.paths.get}")
    private String getPath;

    public ResponseEntity<Object> getBookingById(long userId, Long bookingId) {
        String url = String.format(getPath, bookingId);
        return get(url, userId);
    }
}
```

2024-05-13 23:18 UTC, lap-lik commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +            return ResponseEntity.status(e.getStatusCode()).body(e.getResponseBodyAsByteArray());
Добавил, надеюсь верно понял что требовалось.

2024-05-13 23:23 UTC, lap-lik commented on docker-compose.yml
> +    image: postgres:16.1
В Dockerfile методом тестов и ошибок прописал `FROM amazoncorretto:11-alpine-jdk`. Еще до первой заливки проекта, пробовал указать конкретную версию и это вылилось в 100500% загрузки компа при создании контейнеров и их работе 😂

2024-05-14 08:56 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/client/BookingClient.java
> +        String url = String.format("/owner?state=%s&from=%d&size=%d", state.name(), from, size);
в константы тоже хорошо

молодец, что попытался, 
бесценный опыт получил )

2024-05-14 08:57 UTC, Fleaman777 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
ага, все верно говоришь)

2024-05-14 08:57 UTC, Fleaman777 approved these changes

2024-05-14 09:10 UTC, merged